changelog:
  categories:
    - title: Features
      labels: ["type: enhancement"]
    - title: Fixes
      labels: ["type: bug"]
    - title: Documentation
      labels: ["type: documentation", "area: documentation"]
    - title: Maintenance
      labels: ["type: maintenance", "dependencies"]
    - title: Other changes
      labels: ["*"]
